version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
  pre_build:
    commands:
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm run build-prod
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      # - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - echo "Starting SAM packaging `date` in `pwd`"
      - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
  #post_build:
    #commands:
      # Use Post Build for notifications, git tags and any further customization after build
      # - echo "[Post-Build phase]"
    #  - echo "SAM packaging completed on `date`"
#artifacts:
 # type: zip
 # files:
 #   - packaged.yaml
